version: 2.1

jobs:
  github-zip:
    docker:
      - image: holochain/holonix:latest.master
    steps:
      - checkout
      - run:
          no_output_timeout: 20m
          command: nix-shell --run release-github-zip

workflows:
  version: 2.1

  dist:
    jobs:
      - github-zip:
          filters:
            # branches:
            # ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
